### ISSUE TITLE
Swipe Gestures

### ISSUE THREAD

**Issue by AshuJoshi** [AlanQuatermain/AQGridView#124] opened 2012-03-30 19:54 UTC
I have been working on integrating the AQGridView in my project - and so far it has gone well. I have an application that discovers "devices" on a network using SSDP and then display them in a grid view. I have the basic stuff working. Today I wanted to add gesture recognizers to the code. I managed to get Pinch & Double Tap to be assigned to the AQGridViewCell (ControllerGridViewCell is my class) and then delegate them to AQGridViewController (ControllerGridViewController is my class). This all works pretty well - I can individually catch the gestures on a cell or grid basis. NOW what I wanted to do was to add a gesture recognizer to the AQGridView (my ControllerGridViewController points to controllerGridView class - have tied that using the storyboard). I have tried to add the gesture recognizer in initializer for "controllerGridView" and in "viewDidLoad" but to no avail. That is my gesture function never gets control... below is the code snippet any help will be much appreciated!

In viewDidLoad of ControllerGridViewController [AQGridViewController]:

UISwipeGestureRecognizer *gesture = [[UISwipeGestureRecognizer alloc] initWithTarget:self action:@selector(fourFingerSwipe:)];
    [gesture setDirection:UISwipeGestureRecognizerDirectionDown];
    [gesture setNumberOfTouchesRequired:4];
    [self.controllerGridView addGestureRecognizer:gesture];

Here is the recognizer:
- (void)fourFingerSwipe:(UISwipeGestureRecognizer *)gesture
  {
  
  NSLog(@"this is a swipe");
  if(gesture.state == UISwipeGestureRecognizerDirectionDown)
      NSLog(@"Downward Swipe");
  else {
      NSLog(@"Other Swipe");
  }
  }

**Comment by evadne** [comment] 2012-09-15 01:54
This can probably be solved with gesture recognizer prevention (`-requiresGestureRecognizerToFail:`).  Closing because of how old the issue is — but thanks for reporting.  Feel free to re-open the issue or append more information regarding your solution.  Thanks!

**Closed as completed by evadne** 2012-09-15 01:54 UTC
