### ISSUE TITLE
Insets

### ISSUE THREAD

**Issue by nverinaud** [AlanQuatermain/AQGridView#87] opened 2011-08-29 12:35 UTC
Hi,

I am encountering huge issues when using insets. My cells size is changing each time I reload data.

Here is a piece of log when I set a left inset of 6.4:

‘‘‘
(setDesiredCellSize:) Desired Cell Size: {96, 128}
(cellRectAtIndex:) Left Padding: 6.40
(cellRectAtIndex:) Actual Cell Size: {106, 128}

(cellRectAtIndex:) Left Padding: 6.40
(cellRectAtIndex:) Actual Cell Size: {101, 128}

(cellRectAtIndex:) Left Padding: 6.40
(cellRectAtIndex:) Actual Cell Size: {96, 128}
‘‘‘

Did anyone already used insets ??

**Comment by evadne** [comment] 2012-01-26 22:54
This looks like intended behavior.  Notice that the grid view takes the width of content insets away from the usable width, then it divides the rest evenly and places each cell at the center of the individual rects.

Closing as Intended Behavior.  Feel free to re-open this issue, or to attach some code with an use case :)

**Closed as completed by evadne** 2012-01-26 22:54 UTC
