### ISSUE TITLE
Crash when tapping anywhere, after moving (SpringBoard example)

### ISSUE THREAD

**Issue by DouweM** [AlanQuatermain/AQGridView#11] opened 2010-08-05 09:28 UTC
When you first move a couple of SpringBoard icons, and then tap anywhere in the `AQGridView`, chances are good the app will crash. (This happens in both the SpringBoard example as my own app which uses the basic SpringBoard code to allow the user to move cells)

Why? Because for some reason `hitView` inside `touchesEnded:withEvent:` in `AQGridView.m` doesn't 'contain' a `UIView`, but an object of another type, that doesn't respond to the `superview` selector called on it on line 1287. This obviously results in an `unrecognized selector sent` exception: a crash.

Why `hitView` contains a random object, and not the tapped `UIView` however, I'm not sure... It probably has something to do with `_touchedContentView` not pointing in the right direction, as this is the object that's `retain`ed and then assigned to `hitView`.

PS. Sometimes the app doesn't crash when tapping after moving, this is because you're lucky and `hitView` actually points to an object that responds to `superview`, but it's almost never the `UIView` that `hitView` should be (the tapped view).

**Comment by AlanQuatermain** [comment] 2010-08-16 17:54
This should be fixed by the big update I pushed last week. I can't reproduce it any more, at least.

**Comment by DouweM** [comment] 2010-08-16 17:56
Okay, will check the big update out when I get to my Mac.

**Closed as completed** 2010-08-17 00:54 UTC
